name: permission_analyzer_gui
description: "A template for further flutter projects"  # {{projectDescription}}
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.3.4
  equatable: ^2.0.5
  path: any
  path_provider: any
  isar:
    version: ^3.1.0+1
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: ^3.1.0+1
    hosted: https://pub.isar-community.dev/
  flutter_localization: any
  intl: any
  file_picker: ^8.1.2

  ## playing with graphs!
  # fl_chart (https://pub.dev/packages/fl_chart) (https://app.flchart.dev/#/radar)
  fl_chart: ^0.69.0
  # flutter_graph_view (https://pub.dev/packages/flutter_graph_view)
  flutter_graph_view:
    git: https://github.com/angrycodez/flutter_graph_view
  freezed_annotation: ^2.4.4
  flutter_layout_grid: ^2.0.7
  animated_tree_view: ^2.3.0
  logging: ^1.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.9
  isar_generator:
    version: ^3.1.0+1
    hosted: https://pub.isar-community.dev/
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/